config/routes.rb
Rails.application.routes.draw do
  get "comments/create"
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get '/quotes/random', to: 'quotes#random'


 resources :groups, only: [:index, :new, :create, :show, :destroy] do
  resources :group_memberships, only: [:create]
  resources :goals, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :comments, only: [:create, :update, :destroy]

  resources :goal_completions, only: [] do
    post :update_progress, on: :collection
  end
end




end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @group = Group.find_by(id: params[:group_id])
    @comment = Comment.new(comment_params)
    @comment.group = @group
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to group_path(@group) }
        format.json # Follows the classic Rails flow and look for a create.json view
      else
        format.html { render "groups/show", status: :unprocessable_entity }
        format.json # Follows the classic Rails flow and look for a create.json view
      end
    end

  end

  def destroy
    @comment = Comment.find(params[:id])
    @group = @comment.group
    @comment.destroy
    redirect_to group_path(@group), notice: "comment deleted."

  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(likes: @comment.likes + 1)
    render json: @comment
  end



  private

  def comment_params
    params.require(:comment).permit(:message)
  end


end

app/views/comments/_comments_list.html.erb
<div class="comments mt-3">
  <% comments.each do |comment| %>
    <div class="comment" data-controller="likes" data-likes-url-value="<%= group_comment_url(comment.group, comment)%>" id="comment-<%=comment.id%>" style="display: table; width: 100%; margin-bottom: 15px; padding: 10px; border: 1px solid #e0e0e0; border-radius: 5px;">
      <div style="display: table-cell; width: 100%; vertical-align: top;">
        <h4 style="margin: 0 0 8px 0;"><%= comment.user.username %></h4>
        <p style="margin: 0 0 8px 0;"><%= comment.message %></p>
        <p data-likes-target="likes" style="margin: 0;"><%= comment.likes %>likes</p>
      </div>

      <div style="display: table-cell; vertical-align: top; white-space: nowrap; width: 1px;">
        <%= button_tag(data: { turbo: false, action: "click->likes#save"},
            style: "color: rgb(85, 68, 196); text-decoration: none; padding: 5px; margin-right: 5px;") do %>
          <i class="fa-solid fa-thumbs-up"></i>
        <% end %>
        <%= link_to group_comment_path(comment.group, comment),
            data: { turbo_method: :delete, turbo_confirm: "Delete this comment. Are you sure?" },
            style: "color: #dc3545; text-decoration: none; padding: 5px;" do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>