config/routes.rb
Rails.application.routes.draw do
  get "comments/create"
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get '/quotes/random', to: 'quotes#random'


 resources :groups, only: [:index, :new, :create, :show, :destroy] do
  resources :group_memberships, only: [:create]
  resources :goals, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :comments, only: [:create, :update, :destroy]

  resources :goal_completions, only: [] do
    post :update_progress, on: :collection
  end
end




end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
        <div class="container">
            <div class="footer-nav">
                <ul>
                    <li> <%= link_to "Home", root_path %></li>
                    <li><%= link_to "Login", user_session_path %></li>
                    <li>  <%= link_to "Sign up", new_user_registration_path %></li>

                </ul>
            </div>
            <div class="social-icons">
                <a href="#"><i class="fab fa-youtube"></i></a>
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
        <div class="copyright">
            <p class="copyrighttext">&copy; 2025 - 21 days later</p>
        </div>
    </footer>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="sidebar-wrapper">
    <div data-toggle-navbar-target="sidebar" class="sidebar">

     <div class="d-flex align-items-center position-relative p-3">
  <button class="closebtn" data-action="click->toggle-navbar#close"> &times; </button>

  <div class="logo mx-auto">
  <%= link_to root_path do %>
    <%= image_tag "logo.svg", alt: "test" %>
   <% end %></div>
</div>


      <div class="nav-links">
        <div id="navbar_username" style="display: flex; align-items: center; gap: 40px;">
      <% if current_user&.photo&.attached? %>
         <%= cl_image_tag current_user.photo.key, class: "avatar-bordered", alt: "avatar", height: 40, width: 40, crop: :fill %>
        <% end %>
        <strong><%= current_user.username %></strong>
      </div>


      <%= link_to new_group_path, class: "#{'active' if current_page?(new_group_path)}" do %>
        <i class="fa-solid fa-square-plus"></i> New Group
      <% end %>

      <%= link_to groups_path, class: "#{'active' if current_page?(groups_path)}" do %>
        <i class="fa-solid fa-users"></i> Groups
      <% end %>
<hr>
      <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
  </div>
   <div data-controller="quotes">
  <p data-quotes-target="message" class="loading-message"></p>
  <blockquote class="quote-box">
    <p data-quotes-target="quote" class="quote-text"></p>
    <p data-quotes-target="author" class="quote-author"></p>
  </blockquote>
</div>
</div>
    </div>
  </div>

<i style="font-size:30px; cursor:pointer; display:none; background-color:white; color:purple; padding:10px; border-radius:5px; margin:10px;"
   data-action="click->toggle-navbar#open"
   data-toggle-navbar-target="open"
   class="fa-solid fa-bars open-navbar-icon position-fixed">
</i>

<% end %>